# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

eagles = Team.create(name: "Eagles", logo: "https://media.gettyimages.com/photos/detailed-view-of-the-philadelphia-eagles-logo-prior-to-the-game-the-picture-id1283735950?s=612x612")
dolphins = Team.create(name: "Dolphins", logo: "https://1000logos.net/wp-content/uploads/2021/04/Miami-Dolphins-logo.png")
packers = Team.create(name: "Packers", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Green_Bay_Packers_logo.svg/2560px-Green_Bay_Packers_logo.svg.png")
giants = Team.create(name: "Giants", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/New_York_Giants_logo.svg/2560px-New_York_Giants_logo.svg.png")
patriots = Team.create(name: "Patriots", logo: "https://static.clubs.nfl.com/image/private/f_auto/patriots/ftuml6gmogyahtnd2neb")
vikings = Team.create(name: "Vikings", logo: "https://1000logos.net/wp-content/uploads/2017/06/Minnesota-Vikings-Logo-1965.png")
bills = Team.create(name: "Bills", logo: "https://cdn.freebiesupply.com/images/large/2x/buffalo-bills-football-logo.png")
chiefs = Team.create(name: "Chiefs", logo: "https://i.pinimg.com/originals/c2/47/79/c2477980843e70545a724e34a3ffc120.png")
buccaneers = Team.create(name: "Buccaneers", logo: "https://cdn.freebiesupply.com/images/large/2x/tampa-bay-buccaneers-logo-transparent.png")
raiders = Team.create(name: "Raiders", logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/LV")
saints = Team.create(name: "Saints", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/New_Orleans_Saints_logo.svg/630px-New_Orleans_Saints_logo.svg.png")
broncos = Team.create(name: "Broncos", logo: "https://wp-denverite.s3.amazonaws.com/wp-content/uploads/sites/4/2016/10/Denver_Broncos_logo.svg_-1024x595.png")
bengals = Team.create(name: "Bengals", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Cincinnati_Bengals_logo.svg/2560px-Cincinnati_Bengals_logo.svg.png")
bears = Team.create(name: "Bears", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Chicago_Bears_logo.svg/2560px-Chicago_Bears_logo.svg.png")
seahawks = Team.create(name: "Seahawks", logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/SEA")
niners = Team.create(name: "49ers", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/San_Francisco_49ers_logo.svg/2560px-San_Francisco_49ers_logo.svg.png")
ravens = Team.create(name: "Ravens", logo: "https://logos-world.net/wp-content/uploads/2020/05/Baltimore-Ravens-logo.png")
commanders = Team.create(name: "Commanders", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Washington_Commanders_logo.svg/2560px-Washington_Commanders_logo.svg.png")
cardinals = Team.create(name: "Cardinals", logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/ARI")
browns = Team.create(name: "Browns", logo: "https://wp.usatodaysports.com/wp-content/uploads/sites/90/2015/02/helmet_top_center1.png")
lions = Team.create(name: "Lions", logo: "https://seeklogo.com/images/D/detroit-lions-logo-1741EB43DD-seeklogo.com.png")
colts = Team.create(name: "Colts", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Indianapolis_Colts_logo.svg/800px-Indianapolis_Colts_logo.svg.png")
panthers = Team.create(name: "Panthers", logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/CAR")
jaguars = Team.create(name: "Jaguars", logo: "https://1000logos.net/wp-content/uploads/2018/07/Jacksonville-Jaguars-Logo.png")
chargers = Team.create(name: "Chargers", logo: "https://1000logos.net/wp-content/uploads/2016/11/San-Diego-Chargers-Logo.png")
jets = Team.create(name: "Jets", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/New_York_Jets_logo.svg/1200px-New_York_Jets_logo.svg.png")
titans = Team.create(name: "Titans", logo: "https://logos-world.net/wp-content/uploads/2020/05/Tennessee-Titans-Logo.png")
rams = Team.create(name: "Rams", logo: "https://i.guim.co.uk/img/media/c15695433fb1871e73851c41ad963f3b7c562767/0_164_2000_1200/master/2000.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=7b0b7cbe882fa6e6cb783536ef8875d0")
texans = Team.create(name: "Texans", logo: "https://logos-world.net/wp-content/uploads/2020/05/Houston-Texans-logo.png")
falcons = Team.create(name: "Falcons", logo: "https://cdn.freebiesupply.com/images/thumbs/2x/atlanta-falcons-logo.png")
cowboys = Team.create(name: "Cowboys", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Dallas_Cowboys.svg/1076px-Dallas_Cowboys.svg.png")
steelers = Team.create(name: "Steelers", logo: "https://1000logos.net/wp-content/uploads/2017/06/Pittsburgh-Steelers-Logo.png")

qb = Position.create(name: "Quarterback")
rb = Position.create(name: "Runningback")
wr = Position.create(name: "Wide Reciever")
te = Position.create(name: "Tight End")
k = Position.create(name: "Kicker")
df = Position.create(name: "Defense")

Player.create(name: "Jalen Hurts", image: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/gpz9zs474snz3jntrpbd", team_id: eagles.id, position_id: qb.id, )
Player.create(name: "Tyreek Hill", team_id: dolphins.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3116406.png&w=350&h=254")
Player.create(name: "Aaron Rodgers", team_id: packers.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/8439.png")
Player.create(name: "Saquon Barkley", team_id: giants.id, position_id: rb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3929630.png&w=350&h=254")
Player.create(name: "Patriots", team_id: patriots.id, position_id: df.id, image: "https://static.clubs.nfl.com/image/private/f_auto/patriots/ftuml6gmogyahtnd2neb")
Player.create(name: "Justin Jefferson", team_id: vikings.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4262921.png")
Player.create(name: "Josh Allen", team_id: bills.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3918298.png")
Player.create(name: "Travis Kelce", team_id: chiefs.id, position_id: te.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/15847.png&w=350&h=254")
Player.create(name: "Tom Brady", team_id: buccaneers.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2330.png")
Player.create(name: "Devante Adams", team_id: raiders.id, position_id: wr.id, image: "https://b.fssta.com/uploads/application/nfl/headshots/10550.png")
Player.create(name: "Saints", team_id: saints.id, position_id: df.id, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/New_Orleans_Saints_logo.svg/630px-New_Orleans_Saints_logo.svg.png")
Player.create(name: "Russell Wilson", team_id: broncos.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/14881.png")
Player.create(name: "Joe Mixon", team_id:bengals.id, position_id: rb.id, image: "https://a.espncdn.com/i/headshots/nfl/players/full/3116385.png")
Player.create(name: "Justin Fields", team_id: bears.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362887.png&w=350&h=254")
Player.create(name: "D.K. Metcalf", team_id: seahawks.id, position_id: wr.id, image: "https://static.www.nfl.com/image/private/t_headshot_desktop/league/oa43ir8zoaiofwbupkrt")
Player.create(name: "Brandon Aiyuk", team_id: niners.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360438.png&w=350&h=254")
Player.create(name: "Lamar Jackson", team_id: ravens.id, position_id: qb.id, image: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/gylnuxkxgm3zd4j0d0ku")
Player.create(name: "Terry McLauren", team_id: commanders.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3121422.png&w=350&h=254")
Player.create(name: "Kyler Murray", team_id: cardinals.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3917315.png")
Player.create(name: "Nick Chubb", team_id: browns.id, position_id: rb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128720.png")
Player.create(name: "Amon-Ra St. Brown", team_id: lions.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4374302.png")
Player.create(name: "Jonathan Taylor", team_id: colts.id, position_id: rb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242335.png&w=350&h=254")
Player.create(name: "Christian McCaffrey", team_id: panthers.id, position_id: rb.id, image: "https://a.espncdn.com/i/headshots/nfl/players/full/3117251.png") 
Player.create(name: "Trevor Lawrence", team_id: jaguars.id, position_id: qb.id, image: "https://b.fssta.com/uploads/application/nfl/headshots/22197.png")
Player.create(name: "Justin Herbert", team_id: chargers.id, position_id: qb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4038941.png&w=350&h=254")
Player.create(name: "Garrett Wilson", team_id: jets.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4569618.png")
Player.create(name: "Derrick Henry", team_id: titans.id, position_id: rb.id, image: "https://a.espncdn.com/i/headshots/nfl/players/full/3043078.png")
Player.create(name: "Cooper Kupp", team_id: rams.id, position_id: wr.id, image: "https://b.fssta.com/uploads/application/nfl/headshots/13166.png")
Player.create(name: "Texans", team_id: texans.id, position_id: df.id, image: "https://logos-world.net/wp-content/uploads/2020/05/Houston-Texans-logo.png")
Player.create(name: "Cordarelle Patterson", team_id: falcons.id, position_id: rb.id, image: "https://static.www.nfl.com/image/private/t_headshot_desktop/league/ncyzuofecpl1v63vznp6")
Player.create(name: "CeeDee Lamb", team_id: cowboys.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241389.png&w=350&h=254")
Player.create(name: "Najee Harris", team_id: steelers.id, position_id: rb.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241457.png&w=350&h=254")
Player.create(name: "A.J. Brown", team_id: eagles.id, position_id: wr.id, image: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4047646.png&w=350&h=254")
